### PR TITLE
fix(samples): close firestore instance in test

### PR DESCRIPTION
**Pull request by suraj-qlogic**

### CODE REVIEW

**Review by athakor — APPROVED** [review]

**Review by dmitry-fa — CHANGES_REQUESTED** [review]
1. Please remove 'protected' from close() methods
2. Add closing in the QuickStart.main() method

otherwise looks good

**Comment by suraj-qlogic** [comment]
@dmitry-fa ,For your second comment like ```Add closing in the QuickStart.main() method```,Here main method already close by closing brace.

**Comment by dmitry-fa** [comment]
> 
> 
> @dmitry-fa ,For your second comment like `Add closing in the QuickStart.main() method`,Here main method already close by closing brace.

```
  public static void main(String[] args) throws Exception {
    // default project is will be used if project-id argument is not available
    String projectId = (args.length == 0) ? null : args[0];
    Quickstart quickStart = (projectId != null) ? new Quickstart(projectId) : new Quickstart();
    quickStart.run();
  }
```
please add `quickStart.close();`

**Comment by suraj-qlogic** [comment]
@dmitry-fa ,PTAL

**Review by dmitry-fa — APPROVED** [review]

**Pull request closed without merging**
